apiVersion: apps/v1
kind: Deployment
metadata:
  name: naabu-scanner-deployment
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: naabu-scanner
  template:
    metadata:
      labels:
        app: naabu-scanner
    spec:
      containers:
      - name: naabu-scanner
        image: your-naabu-scanner-image-here
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_URL
        - name: NAABU_CONCURRENCY
          value: "100"
        - name: NAABU_RATE
          value: "10000"
        - name: NAABU_RETRIES
          value: "0"
        - name: NAABU_TIMEOUT
          value: "1000"
